trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

steps:
- script: |
    dotnet tool install --tool-path .paket Paket
    .paket/paket install
  displayName: 'Install Paket'
- script: dotnet restore #Necessary to explicitly restore first
  displayName: 'dotnet restore'
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
